apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizzes-backend-deployment
spec:
  selector:
    matchLabels:
      app: quizzes-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: quizzes-backend
    spec:
      containers:
      - name: quizzes-backend
        image: ${BACKEND_IMAGE}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: backend-http
          containerPort: 3000
        - name: ws
          containerPort: 7000
        env:
          - name: REDIS_HOST
            value: "quizzes-backend-redis-master.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quizzes-backend-redis
                key: redis-password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_DATABASE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_USERNAME
          - name: KAFKA_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: KAFKA_HOST
          - name: MESSAGE_FORMAT_VERSION
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: MESSAGE_FORMAT_VERSION
          - name: SERVICE_ID
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: SERVICE_ID
      initContainers:
      - name: quizzes-backend-run-migrations
        image: ${BACKEND_IMAGE}
        command: ['sh', '-c', 'cd /app && yarn typeorm migration:run']
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_DATABASE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-database-secret
                key: POSTGRES_USERNAME
